////  Watchdog Timer Registers
//WDT_w = 0xBF800000
//    .global WDT_w
////  Real Time Clock Registers
//RTCC_w = 0xBF800200
//    .global RTCC_w
////  Timer 1 Registers
//TRM1_w = 0xBF800600
//    .global TRM1_w
////  Timer 2 Registers
//TMR2_w = 0xBF800800
//    .global TMR2_w
////  Timer 3 Registers
//TMR3_w = 0xBF800A00
//    .global TMR3_w
////  Timer 4 Registers
//TMR4_w = 0xBF800C00
//    .global TMR4_w
////  Timer 5 Registers
//TMR5_w = 0xBF800E00
//    .global TMR5_w
////  Input Capture 1 Registers
//IC1_w = 0xBF802000
//    .global IC1_w
////  Input Capture 2 Registers
//IC2_w = 0xBF802200
//    .global IC2_w
////  Input Capture 3 Registers
//IC3_w = 0xBF802400
//    .global IC3_w
////  Input Capture 4 Registers
//IC4_w = 0xBF802600
//    .global IC4_w
////  Input Capture 5 Registers
//IC5_w = 0xBF802800
//    .global IC5_w
////  Output Compare 1 Registers
//OC1_w = 0xBF803000
//    .global OC1_w
////  Output Compare 2 Registers
//OC2_w = 0xBF803200
//    .global OC2_w
////  Output Compare 3 Registers
//OC3_w = 0xBF803400
//    .global OC3_w
////  Output Compare 4 Registers
//OC4_w = 0xBF803600
//    .global OC4_w
////  Output Compare 5 Registers
//OC5_w = 0xBF803800
//    .global OC5_w
////  Inter-Integrated Circuit 1 Registers
//I2C1_w = 0xBF805000;
//    .global I2C1_w
////  Inter-Integrated Circuit 2 Registers
//I2C2_w = 0xBF805100;
//    .global I2C2_w
////  Serial Peripheral Interface 1 Registers
//SPI1_w = 0xBF805800
//    .global SPI1_w
////  Serial Peripheral Interface 2 Registers
//SPI2_w = 0xBF805A00
//    .global SPI2_w
////  Uneversal Asynchronous Receiver Transmitter 1 Registers
//UART1_w = 0xBF806000
//    .global UART1_w
////  Uneversal Asynchronous Receiver Transmitter 2 Registers
//UART2_w = 0xBF806200
//    .global UART2_w
////  Parallel Master Port Registers
//PMP_w = 0xBF807000
//    .global PMP_w
////  Analog To Digital Converter Registers
//ADC_w = 0xBF809000
//    .global ADC_w
////  Comparator Voltage Reference Registers
//CVRef_w = 0xBF809800
//    .global CVRef_w
////  Comparator Registers
//CM_w = 0xBF80A000
//    .global CM_w
////  Charge Time Measurement Unit Registers
//CMTU_w = 0xBF80A200
//    .global CMTU_w
////  Oscillator Registers
//OSC_w = 0xBF80F000
//    .global OSC_w